services:
#   licence_service:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     depends_on:
#       - postgres
#     ports:
#       - "8080:8080"
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Production
#       - ConnectionString=User Id=postgres;Password=123123; Host=postgres;Port=5432;Database=LicenseDb;
#       - passPhrase="dfb2asdfsadfgasdfgsaduqfgbsdufbsadufbsquayvdffd"
    
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=123123
        - POSTGRES_USER=postgres
        - POSTGRES_DB=LicenseDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
